main: mp.dottiewh.DottUtils
version: 1.1.7b
name: DottUtils
author: Dottiewh
api-version: 1.13

commands:
  dottutils:
    description: Comando principal del plugin.
    usage: /dottutils
    aliases:
      - du
      - dutils
    permission: dottUtils.dutils
    permission-message: No puedes usar esto.
  gm:
    description: Abreviaciones del gamemode.
    usage: /gm
    permission: dottUtils.gamemode
    permission-message: No puedes usar esto.
  jump:
    description: Te deja saltar.
    usage: /jump
    permission: dottUtils.gamemode
    permission-message: No puedes usar esto.
  status:
    description: Muestra tps y otros datos
    usage: /status