main: mp.dottiewh.DottUtils
version: 1.0.1
name: DottUtils
author: Dottiewh
api-version: 1.13

commands:
  gm:
    description: Abreviaciones del gamemode.
    usage: /gm
    permission: miPlugin.gamemode
    permission-message: No puedes usar esto.