main: mp.dottiewh.DottUtils
version: 1.2.3
name: DottUtils
author: Dottiewh
api-version: 1.13
softdepend: ["DiscordSRV"]

commands:
  dottutils:
    description: Comando principal del plugin.
    usage: /dottutils
    aliases:
      - du
      - dutils
    permission: dottUtils.dutils
    permission-message: No puedes usar esto.
  gm:
    description: Abreviaciones del gamemode.
    usage: /gm
    permission: dottUtils.gamemode
    permission-message: No puedes usar esto.
  adminchat:
    description: Adminchat
    usage: /adminchat
    aliases:
      - ac
      - achat
  repair:
    description: Te repara la herramienta en mano al màximo
    usage: /repair
    aliases:
      - fix
    permission: dottUtils.repair
    permission-message: No puedes usar esto.
  heal:
    description: Te cura la vida completa.
    usage: /heal
    permission: dottUtils.heal
    permission-message: No puedes usar esto.
  feed:
    description: Te pone el hambre totalmente satisfecha.
    usage: /feed
    permission: dottUtils.feed
    permission-message: No puedes usar esto.
  countdown:
    description: Hace una cuenta atrás.
    usage: /countdown
    permission: dottUtils.countdown
    permission-message: No puedes usar esto.
  jump:
    description: Te deja saltar.
    usage: /jump
    permission: dottUtils.jump
    permission-message: No puedes usar esto.
  status:
    description: Muestra tps y otros datos
    usage: /status
  back:
    description: Te teletransporta a tu último punto de muerte.
    usage: /back
  tpa:
    description: Manda solicitudes de tpa.
    usage: /tpa
  tpaaccept:
    description: Acepta solicitudes de tpa.
    usage: /tpaacept
  tpadeny:
    description: Rechaza solicitudes de tpa.
    usage: /tpadeny
  tpacancel:
    description: Cancela solicitudes de tpa.
    usage: /tpacancel
  playtime:
    description: Puedes ver tu tiempo de juego o el de otros.
    usage: /playtime
  coords:
    description: Comando principal del plugin.
    usage: /coords